version: '3.4'

services:
  codax:
    image: codax
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 tests/containers/cont1_ReDos/server.py "]
    ports:
      - 5678:5678
